[package]
name = "betterpdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
lopdf = "*"


[[bin]]
name = "betterpdf"
path = "src/application/main.rs"

